lastBackupDate: "2022-06-21T01:47:09.681083Z"
currentBackupDate: "2022-06-21T01:47:09.681083Z"
rootFolderPath: "/home/tihe/Desktop/test"
rootFolderByYear: "/home/tihe/Desktop/test/2022"
applicationName: "gleaming-mason-352503"
googleMimeTypes:
  application/vnd.google-apps.document:
    exportFormat: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    fileExtension: ".docx"
  application/vnd.google-apps.spreadsheet:
    exportFormat: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    fileExtension: ".xlsx"
  application/vnd.google-apps.presentation:
    exportFormat: "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    fileExtension: ".pptx"
fields:
  files: "nextPageToken, files(id, name, mimeType, parents, modifiedTime, shortcutDetails)"
  file: "id, name, mimeType, parents, modifiedTime"
query:
  folder: "mimeType='application/vnd.google-apps.folder' and modifiedTime > '%s' and\
    \ trashed=false"
  file: "mimeType!='application/vnd.google-apps.folder' and mimeType!='application/vnd.google-apps.shortcut'\
    \ and mimeType!='application/vnd.google-apps.map' and modifiedTime > '%s' and\
    \ trashed=false"
